---
title: Minimal Text
baseUrl: "/"
url: "https://danchinaski.github.io/"
desc: A minimal blog for off-topic blog entries.
about: I am a web developer, software engineer, and project manager currently living in Collinsville, Illinois. I'm a little weird but pretty friendly.
image: https://pbs.twimg.com/profile_images/378800000828997628/cbf39ea105c32d05c4ed0450a50dfde0_400x400.jpeg
excerpt_separator: "<!-- more -->"
markdown: kramdown
gems:
- jekyll-paginate
exclude:
  - .jekyll-metadata
  - README.md
  - CNAME
paginate: 5
paginate_path: "/:num/"
highlighter: rouge
permalink: pretty
